import Head from "next/head";
import Image from "next/image";
import HeadHero from "../components/home/head";
import Articles from "../components/home/articles";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>
      <HeadHero />
      <Articles/>
    </div>
  );
}
